"""add members and member events

Revision ID: 6fc79064ec16
Revises: 5f610f0c9186
Create Date: 2026-06-07 17:29:40.606930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc79064ec16'
down_revision: Union[str, Sequence[str], None] = '5f610f0c9186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_events', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'member_events', 'members', ['member_id'], ['id'])
    op.add_column('members', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('members', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('members', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_members_channel_user', 'members', ['channel_id', 'telegram_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_members_channel_user', 'members', type_='unique')
    op.drop_column('members', 'updated_at')
    op.drop_column('members', 'left_at')
    op.drop_column('members', 'joined_at')
    op.drop_constraint(None, 'member_events', type_='foreignkey')
    op.drop_column('member_events', 'member_id')
    # ### end Alembic commands ###
