"""add post stats tables

Revision ID: 858b260212a8
Revises: b3c5f2247cf1
Create Date: 2026-06-09 12:06:24.925983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858b260212a8'
down_revision: Union[str, Sequence[str], None] = 'b3c5f2247cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('telegram_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=False),
    sa.Column('text_preview', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'telegram_message_id', name='uq_posts_channel_message')
    )
    op.create_index(op.f('ix_posts_channel_id'), 'posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_telegram_channel_id'), 'posts', ['telegram_channel_id'], unique=False)
    op.create_index(op.f('ix_posts_telegram_message_id'), 'posts', ['telegram_message_id'], unique=False)
    op.create_table('post_stats_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('forwards', sa.Integer(), nullable=True),
    sa.Column('reactions_count', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_stats_snapshots_id'), 'post_stats_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_post_stats_snapshots_post_id'), 'post_stats_snapshots', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_stats_snapshots_post_id'), table_name='post_stats_snapshots')
    op.drop_index(op.f('ix_post_stats_snapshots_id'), table_name='post_stats_snapshots')
    op.drop_table('post_stats_snapshots')
    op.drop_index(op.f('ix_posts_telegram_message_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_telegram_channel_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_channel_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
